booking/urls.py
from django.urls import path

from . import views

app_name= 'booking'
urlpatterns = [
    path('', views.Search.as_view(), name='search'),
    path('results/', views.results, name='results'),
    path('reserve/<int:room_id>/', views.reserve, name='reserve'),
    path('reservations/', views.reservations, name='reservations'),
    path('detail/<int:booking_id>/', views.detail, name='detail'),
    path('detail/<int:booking_id>/pdf', views.BookingPdf.as_view(), name='bookingPdf'),
    path('error/', views.Error.as_view(), name='error'),
]

chapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('booking.urls')),
    path('admin/', admin.site.urls),
]

booking/models.py
import datetime, uuid
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Room(models.Model):
    """
    Stores a room entry
    """
    type_text = models.CharField(max_length=200)
    available_date = models.DateField()
    price_number = models.FloatField()
    description_text = models.CharField(max_length=1000)

    def __str__(self):
        return '{type} room, price:{price}'.format(type=self.type_text,price=self.price_number)


class Booking(models.Model):
    """
    Stores a reservation entry related to a room and a user
    """
    room = models.ForeignKey(Room, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    code = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    amount_number = models.FloatField()
    days_number = models.IntegerField()
    payment_card_text = models.CharField(max_length=20)
    phone_number_text = models.CharField(max_length=20)
    comment_text = models.CharField(max_length=1000, null=True)
    name_text = models.CharField(max_length=60)
    surname_text = models.CharField(max_length=60)
    id_card_text = models.CharField(max_length=20)
    email = models.EmailField()
    date = models.DateField()
    from_date = models.DateField()
    to_date = models.DateField()

    def __str__(self):
        return '{}'.format(self.code)

booking/views.py
from datetime import datetime
import io
from django.views import generic, View
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Room, Booking
from .render import Render

class Search(View):
    """
    Display a search form.

    **Template:**

    :template:`booking/search.html`
    """
    def get(self, request):
        template_name = "booking/search.html"
        return render(request, template_name)


def results(request):
    """
    Display the room results in a date range

    **Context**

    ``rooms``
        All the available rooms.

    ``total_days``
        Total days of stay.

    **Template:**

    :template:`booking/results.html`
    """
    try:
        from_date = request.GET['fromDate']
        to_date = request.GET['toDate']
    except:
        return redirect('error')
    else:
        date_format = '%Y-%m-%d'
        rooms = Room.objects.filter(available_date__range=[from_date, to_date])
        from_date_formatted = datetime.strptime(from_date, date_format )
        to_date_formatted = datetime.strptime(to_date, date_format)
        total_days = (to_date_formatted - from_date_formatted).days
        #Variables for other views
        request.session['total_days'] = total_days
        request.session['from_date'] = from_date
        request.session['to_date'] = to_date
        return render(request, 'booking/results.html', {'rooms' : rooms, 'total_days': total_days})


def reserve(request, room_id):
    """
    Display the reserve form.

    **Context**

    ``room``
        An instance of the selected room.

    **Template:**

    :template:`booking/reserve.html`
    """
    room = get_object_or_404(Room, pk=room_id)
    return render(request, 'booking/reserve.html', {'room': room})


def reservations(request):
    """
    Display all the reservations of the user.

    **Context**

    ``reservations``
        All the reservations of the user.

    **Template:**

    :template:`booking/reservations.html`
    """
    user = request.user
    reservations = Booking.objects.filter(user=user)
    if request.method == 'POST':
        try:
            name = request.POST['name']
            surname = request.POST['surname']
            email = request.POST['email']
            credit_card = request.POST['creditCard']
            comment = request.POST['comment']
            phone = request.POST['phone']
            id_card = request.POST['idCard']
            room_id = request.POST['roomId']
            room = get_object_or_404(Room, pk=room_id)
            total_days = request.session.get('total_days')
            from_date=request.session.get('from_date')
            to_date=request.session.get('to_date')
            room_price = request.POST['roomPrice']
            user = request.user
            date = datetime.now().date()
            amount = total_days * float(room_price)
        except:
            return redirect('booking:error')
        else:
            reservation = Booking(
                            name_text=name,
                            surname_text=surname,
                            id_card_text=id_card,
                            email=email,
                            comment_text=comment,
                            phone_number_text=phone,
                            payment_card_text=credit_card,
                            days_number=total_days,
                            amount_number=amount,
                            from_date=from_date,
                            to_date=to_date,
                            date=date,
                            room=room,
                            user=user)
            reservation.save()
            room.available_date = to_date
            room.save()

    return render(request, 'booking/reservations.html', {'reservations': reservations})


def detail(request, booking_id):
    """
    Display the detail view of a reservation.

    **Context**

    ``reservation``
        The selected reservation.

    **Template:**

    :template:`booking/detail.html`
    """
    reservation = get_object_or_404(Booking, pk=booking_id)
    return render(request, 'booking/detail.html', {'reservation': reservation})


class BookingPdf(View):
    """
    Generate and display the pdf of one reservation details.

    **Context**

    ``reservation``
        An instance of the selected reservation.

    **Template:**

    :template:`booking/pdf.html`
    """
    def get(self, request, booking_id):
        reservation = get_object_or_404(Booking, pk=booking_id)
        params = {
            'reservation': reservation,
            'request': request
        }
        return Render.render('booking/pdf.html', params)

class Error(View):
    """
    Display a error view.

    **Template:**

    :template:`booking/error.html`
    """
    def get(self, request):
        template_name = "booking/error.html"
        return render(request, template_name)

booking/templates/booking/detail.html
{% extends "booking/layouts/base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'booking/css/detail.css' %}">
  <div class="container">
    <div class="card mx-auto">
      <div class="card-body">
        <h5 class="card-title text-center">Reserva</h5>
        <p class="card-text">
          <div class="row">
            <div class="col-6">
              <p>Nombre: {{ reservation.name_text }}</p>
            </div>
            <div class="col-6">
              <p>Apellidos: {{ reservation.surname_text }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <p>DNI: {{ reservation.id_card_text }}</p>
            </div>
            <div class="col-6">
              <p>Email: {{ reservation.email }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <p>Teléfono: {{ reservation.phone_number_text }}</p>
            </div>
            <div class="col-6">
              <p>Tarjeta de crédito: {{ reservation.payment_card_text }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <p>Total: {{ reservation.amount_number }}</p>
            </div>
            <div class="col-6">
              <p>Fecha de compra: {{ reservation.date }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <p>Desde: {{ reservation.from_date }}</p>
            </div>
            <div class="col-6">
              <p>Hasta: {{ reservation.to_date }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <p>Habitación {{ reservation.room.type_text }}</p>
            </div>
            <div class="col-6">
              <p>Precio por noche: {{ reservation.room.price_number }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <p>Código de reserva: {{ reservation.code }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <p>Comentario: {{ reservation.comment_text }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12 text-center button">
              <a class="btn btn-dark" href="{% url 'booking:bookingPdf' reservation.id %}">Ver en PDF</a>
            </div>
          </div>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

booking/templates/booking/error.html
{% extends "booking/layouts/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'booking/css/error.css' %}">
{% block content %}
<div class="container">
  <h1 class="text-center">Ha ocurrido un error</h1>
  <h6 class="text-center">Dirígete al incio</h6>
</div>
{% endblock %}

booking/templates/booking/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>Chapp booking</title>
      <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
  </head>
  <body>
      {% load static %}
      {% include 'booking/layouts/navbar.html' %}
      {% block content %}{% endblock %}
      <link rel="stylesheet" type="text/css" href="{% static 'booking/css/style.css' %}">
      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous">
      </script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous">
      </script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous">
      </script>
  </body>
</html>

booking/templates/booking/layouts/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" style="color:white;">Chapp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'booking:search' %}">Buscar habitaciones</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'booking:reservations' %}">Reservas</a>
      </li>
    </ul>
  </div>
</nav>

booking/templates/booking/pdf.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Reserva</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }
    </style>
</head>
<body>
  <div class="container">
    <h5>Reserva</h5>
    <p>Código de reserva: {{ reservation.code }}</p>
    <p>Nombre: {{ reservation.name_text }}</p>
    <p>Apellidos: {{ reservation.surname_text }}</p>
    <p>DNI: {{ reservation.id_card_text }}</p>
    <p>Email: {{ reservation.email }}</p>
    <p>Teléfono: {{ reservation.phone_number_text }}</p>
    <p>Tarjeta de crédito: {{ reservation.payment_card_text }}</p>
    <p>Fecha de compra: {{ reservation.date }}</p>
    <p>Fecha de reserva: {{ reservation.from_date }} - {{ reservation.to_date }}</p>
    <p>Habitación {{ reservation.room.type_text }}</p>
    <p>Precio por noche: {{ reservation.room.price_number }}</p>
    <p>Comentario: {{ reservation.comment_text }}</p>
    <p>Total: {{ reservation.amount_number }}</p>
  </div>
</body>
</html>

booking/templates/booking/reservations.html
{% extends "booking/layouts/base.html" %}
{% load static %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'booking/css/reservations.css' %}">
  <div class="d-flex flex-row flex-wrap">
    {% for reservation in reservations %}
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ reservation.code }}</h5>
          <p class="card-text">
            <div class="row">
              <div class="col-6">
                <p>Habitación {{ reservation.room.type_text }}</p>
              </div>
              <div class="col-6">
                <p>Tarjeta: {{ reservation.payment_card_text }}</p>
              </div>
              <div class="col-6">
                <p>Total: {{ reservation.amount_number }}</p>
              </div>
              <div class="col-6">
                <p>Fecha de reserva: {{ reservation.date }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-12 text-center button">
                <a class="btn btn-dark" href="{% url 'booking:detail' reservation.id %}">Ver detalles</a>
              </div>
            </div>
          </p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

booking/templates/booking/reserve.html
{% extends "booking/layouts/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'booking/css/reserve.css' %}">
<div class="container">
  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title text-center">Introduce los datos de reserva</h5>
      <p class="card-text">
        <form action="{% url 'booking:reservations' %}" method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-6">
              <label for="name">Nombre: </label>
              <input class="form-control" type="text" name="name" required></input>
            </div>
            <div class="col-6">
              <label for="surname">Apellidos: </label>
              <input class="form-control" type="text" name="surname" required></input>
            </div>
          </div>
          <div class="form-row">
            <div class="col-4">
              <label for="id">DNI: </label>
              <input class="form-control" type="text" name="idCard" required></input>
            </div>
            <div class="col-8">
              <label for="name">Email: </label>
              <input class="form-control" type="email" name="email" required></input>
            </div>
          </div>
          <div class="form-row">
            <div class="col-6">
              <label for="phone">Teléfono: </label>
              <input class="form-control" type="text" name="phone"  required></input>
            </div>
            <div class="col-6">
              <label for="creditCard">Tarjeta de crédito: </label>
              <input class="form-control" type="text" name="creditCard" required></input>
            </div>
          </div>
          <div class="form-row">
            <div class="col-12">
              <label for="comment">Si lo desea puede dejar un comentario</label>
              <textarea class="form-control" rows="5" name="comment"></textarea>
              <input type="hidden" name="roomPrice" value="{{ room.price_number }}"></input>
              <input type="hidden" name="roomId" value="{{ room.id }}"></input>
            </div>
          </div>
          <div class="form-row">
            <div class="col-12 text-center button">
              <input type="submit" class="btn btn-dark" value="Reservar">
            </div>
          </div>
        </form>
      </p>
    </div>
  </div>
</div>
{% endblock %}

booking/templates/booking/results.html
{% extends "booking/layouts/base.html" %}
{% load static %}
{% load mathfilters %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'booking/css/results.css' %}">
<div class="d-flex flex-row flex-wrap">
  {% for room in rooms %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Habitación {{ room.type_text }}</h5>
        <p class="card-text">
          <div class="row">
            <div class="col-12">
              <p>{{ room.description_text }}</p>
            </div>
            <div class="col-6">
              <p>{{ room.price_number }}€/noche</p>
            </div>
            <div class="col-6">
              <p>Total {{ total_days | mul:room.price_number }}€</p>
            </div>
          </div>
          <div class="row">
            <div class="col-12 text-center button">
              <a class="btn btn-dark"  href="{% url 'booking:reserve' room.id %}">Reservar</a>
            </div>
          </div>
        </p>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

booking/templates/booking/search.html
{% extends "booking/layouts/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'booking/css/search.css' %}">
<div class="container">
  <div class="card mx-auto">
    <div class="card-body">
      <h5 class="card-title text-center">Selecciona un rango de fechas</h5>
      <p class="card-text">
        <form action="{% url 'booking:results' %}" method="get">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-6">
              <input class="form-control" type="date" name="fromDate" required></input>
            </div>
            <div class="col-6">
              <input class="form-control" type="date" name="toDate" required></input>
            </div>
          </div>
          <div class="from-row">
            <div class="col-12 text-center button">
              <input type="submit" class="btn btn-dark" value="Buscar">
            </div>
          </div>
        </form>
      </p>
    </div>
  </div>
</div>
{% endblock %}